BEGIN;

CREATE TABLE IF NOT EXISTS measurement_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE recipes
    ADD COLUMN IF NOT EXISTS prep_time_minutes INTEGER NOT NULL DEFAULT 30;

ALTER TABLE recipes
    DROP CONSTRAINT IF EXISTS recipes_prep_time_minutes_check;

ALTER TABLE recipes
    ADD CONSTRAINT recipes_prep_time_minutes_check
    CHECK (prep_time_minutes > 0 AND prep_time_minutes <= 1440);

CREATE TABLE IF NOT EXISTS favorites (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (recipe_id, user_id)
);

CREATE TABLE IF NOT EXISTS ratings (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (recipe_id, user_id)
);

INSERT INTO actions (code, description) VALUES
    ('favorite.saved', 'Recipe saved to favorites'),
    ('favorite.removed', 'Recipe removed from favorites'),
    ('rating.saved', 'Recipe rating saved')
ON CONFLICT (code) DO NOTHING;

INSERT INTO measurement_units (code, label, sort_order) VALUES
    ('g', 'g', 10),
    ('kg', 'kg', 20),
    ('ml', 'ml', 30),
    ('l', 'l', 40),
    ('kom', 'kom', 50),
    ('žlica', 'žlica', 60),
    ('žličica', 'žličica', 70),
    ('šalica', 'šalica', 80),
    ('prstohvat', 'prstohvat', 90),
    ('pakiranje', 'pakiranje', 100),
    ('vrećica', 'vrećica', 110),
    ('list', 'list', 120),
    ('režanj', 'režanj', 130)
ON CONFLICT (code) DO UPDATE SET
    label = EXCLUDED.label,
    sort_order = EXCLUDED.sort_order;

COMMIT;
