-- LetsCook initial PostgreSQL schema.
-- Apply to an empty database with: psql "$DATABASE_URL" -f db/schema.sql

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TYPE user_role AS ENUM ('user', 'moderator', 'administrator', 'superadmin');
CREATE TYPE recipe_relation_type AS ENUM ('variation', 'clone');
CREATE TYPE media_scan_status AS ENUM ('pending', 'clean', 'infected', 'failed');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    password_hash TEXT,
    oauth_provider TEXT,
    oauth_subject TEXT,
    role user_role NOT NULL DEFAULT 'user',
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    banned_id BIGINT,
    email_verified_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_oauth_unique UNIQUE (oauth_provider, oauth_subject),
    CONSTRAINT users_superadmin_role CHECK (id <> 1 OR role = 'superadmin')
);

CREATE TABLE actions (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL
);

CREATE TABLE action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip_address INET,
    action_id SMALLINT NOT NULL REFERENCES actions(id),
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    target_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE users
    ADD CONSTRAINT users_banned_id_fkey FOREIGN KEY (banned_id) REFERENCES action_log(id) ON DELETE SET NULL;

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    language CHAR(2) NOT NULL DEFAULT 'en',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE category_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    language CHAR(2) NOT NULL,
    name TEXT NOT NULL,
    UNIQUE (category_id, language)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    language CHAR(2) NOT NULL DEFAULT 'en',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tag_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    language CHAR(2) NOT NULL,
    name TEXT NOT NULL,
    UNIQUE (tag_id, language)
);

CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL UNIQUE,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ingredient_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    language CHAR(2) NOT NULL,
    name TEXT NOT NULL,
    UNIQUE (ingredient_id, language),
    UNIQUE (language, name)
);

CREATE TABLE measurement_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    language CHAR(2) NOT NULL DEFAULT 'en',
    steps_html TEXT NOT NULL,
    content_markdown TEXT NOT NULL DEFAULT '',
    main_media_id BIGINT,
    prep_time_minutes INTEGER CHECK (prep_time_minutes > 0 AND prep_time_minutes <= 1440),
    servings NUMERIC(8,2) CHECK (servings > 0),
    author_complexity SMALLINT CHECK (author_complexity BETWEEN 1 AND 5),
    verified BOOLEAN NOT NULL DEFAULT TRUE,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_id BIGINT REFERENCES action_log(id) ON DELETE SET NULL,
    deleted_id BIGINT REFERENCES action_log(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE recipe_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    language CHAR(2) NOT NULL,
    title TEXT NOT NULL,
    UNIQUE (recipe_id, language)
);

CREATE TABLE recipe_tags (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, tag_id)
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE RESTRICT,
    amount NUMERIC(12,3),
    unit TEXT,
    note TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ratings (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (recipe_id, user_id)
);

CREATE TABLE complexity_votes (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    complexity SMALLINT NOT NULL CHECK (complexity BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (recipe_id, user_id)
);

CREATE TABLE favorites (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (recipe_id, user_id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    body TEXT NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_id BIGINT REFERENCES action_log(id) ON DELETE SET NULL,
    deleted_id BIGINT REFERENCES action_log(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE recipe_relations (
    parent_recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    child_recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    relation_type recipe_relation_type NOT NULL DEFAULT 'variation',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (parent_recipe_id, child_recipe_id),
    CONSTRAINT recipe_relations_no_self CHECK (parent_recipe_id <> child_recipe_id)
);

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    recipe_id BIGINT REFERENCES recipes(id) ON DELETE SET NULL,
    original_filename TEXT NOT NULL,
    stored_filename TEXT NOT NULL UNIQUE,
    mime_type TEXT NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    width INTEGER,
    height INTEGER,
    storage_path TEXT NOT NULL,
    variants JSONB NOT NULL DEFAULT '{}'::jsonb,
    checksum_sha256 TEXT,
    scan_status media_scan_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE recipes
    ADD CONSTRAINT recipes_main_media_id_fkey FOREIGN KEY (main_media_id) REFERENCES media(id) ON DELETE SET NULL;

CREATE TABLE views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ip_address INET,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX action_log_created_at_idx ON action_log (created_at DESC);
CREATE INDEX action_log_actor_idx ON action_log (actor_user_id, created_at DESC);
CREATE INDEX action_log_extra_gin_idx ON action_log USING GIN (extra);
CREATE INDEX recipes_visible_idx ON recipes (deleted, hidden, created_at DESC);
CREATE INDEX recipes_title_trgm_idx ON recipes USING GIN (title gin_trgm_ops);
CREATE INDEX recipes_steps_trgm_idx ON recipes USING GIN (steps_html gin_trgm_ops);
CREATE INDEX comments_recipe_visible_idx ON comments (recipe_id, deleted, hidden, created_at DESC);
CREATE INDEX ingredient_translations_name_trgm_idx ON ingredient_translations USING GIN (name gin_trgm_ops);
CREATE INDEX tags_name_trgm_idx ON tags USING GIN (name gin_trgm_ops);
CREATE INDEX media_scan_status_idx ON media (scan_status);

INSERT INTO actions (code, description) VALUES
    ('auth.registered', 'User registered'),
    ('auth.logged_in', 'User logged in'),
    ('auth.logged_out', 'User logged out'),
    ('recipe.created', 'Recipe created'),
    ('recipe.updated', 'Recipe updated'),
    ('recipe.verified', 'Recipe verified or unverified'),
    ('recipe.hidden', 'Recipe hidden'),
    ('recipe.deleted', 'Recipe marked deleted'),
    ('comment.created', 'Comment created'),
    ('comment.hidden', 'Comment hidden'),
    ('comment.deleted', 'Comment marked deleted'),
    ('favorite.saved', 'Recipe saved to favorites'),
    ('favorite.removed', 'Recipe removed from favorites'),
    ('rating.saved', 'Recipe rating saved'),
    ('complexity.saved', 'Recipe complexity vote saved'),
    ('media.uploaded', 'Media uploaded'),
    ('user.banned', 'User banned'),
    ('user.role_promoted', 'User role promoted'),
    ('user.role_changed', 'User role changed')
ON CONFLICT (code) DO NOTHING;

INSERT INTO measurement_units (code, label, sort_order) VALUES
    ('g', 'g', 10),
    ('kg', 'kg', 20),
    ('ml', 'ml', 30),
    ('l', 'l', 40),
    ('kom', 'kom', 50),
    ('žlica', 'žlica', 60),
    ('žličica', 'žličica', 70),
    ('šalica', 'šalica', 80),
    ('prstohvat', 'prstohvat', 90),
    ('pakiranje', 'pakiranje', 100),
    ('vrećica', 'vrećica', 110),
    ('list', 'list', 120),
    ('režanj', 'režanj', 130),
    ('oz', 'oz', 140),
    ('lb', 'lb', 150),
    ('fl_oz', 'fl oz', 160),
    ('tsp', 'tsp', 170),
    ('tbsp', 'tbsp', 180),
    ('cup', 'cup', 190),
    ('pt', 'pint', 200),
    ('qt', 'quart', 210),
    ('gal', 'gallon', 220)
ON CONFLICT (code) DO NOTHING;

INSERT INTO users (id, email, display_name, role)
VALUES (1, 'superadmin@example.local', 'SuperAdmin', 'superadmin')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), GREATEST((SELECT MAX(id) FROM users), 1));

COMMIT;
